### PR TITLE
According to the documentation the minimum qt version is 4.4

### PR DESCRIPTION
**Pull request by marcelotrevisani**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by marcelotrevisani** [comment]
@conda-forge-admin , please rerender

**Comment by marcelotrevisani** [comment]
@conda-forge-admin , please rerender

**Comment by marcelotrevisani** [comment]
@conda-forge-admin , please rerender

**Comment by marcelotrevisani** [comment]
@jschueller Could you please review?

**Comment by marcelotrevisani** [comment]
cc: @conda-forge/qwt

**Comment by jschueller** [comment]
looks good, lets wait for travis

**Comment by jschueller** [comment]
I dont think we're supposed to build qt4 binairies, could you remove the qt_version and rerender ?

**Comment by marcelotrevisani** [comment]
@conda-forge-admin , please rerender

**Comment by marcelotrevisani** [comment]
Failed in ``osx`` for ``qt4``, so I will disable that.

**Comment by marcelotrevisani** [comment]
@conda-forge-admin , please rerender

**Comment by marcelotrevisani** [comment]
A lot of projects still use qt4 or support it, so, I think would be good to build packages for qt4.

**Pull request closed without merging**
