### PR TITLE
V6.1.3 rerender and OSX fix (?)

### PR DESCRIPTION
**Pull request by ceholden**
Hoping this will upgrade the version and make headway toward addressing linking issue on OSX build seen in Travis' try at #5.

Error message
```
linking ../lib/libqwt.6.1.2.dylib
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [../lib/libqwt.6.1.2.dylib] Error 1
make: *** [sub-src-make_default-ordered] Error 2
```

### CODE REVIEW

**Comment by jschueller** [comment]
I guess this can be merged now for me to rebase.

**Comment by jschueller** [comment]
I dont see the failure anyway, are you sure this fixes something ?

**Comment by ceholden** [comment]
The failed build I saw was one of the [initial ones from your PR](https://travis-ci.org/conda-forge/qwt-feedstock/builds/211358127), but it appears to have been a fluke as the latest tries from your PR have passed.

Thanks for the suggestion for adding `toolchain` - I hadn't noticed the addition but:
``` python
# if your project compiles code (such as a C extension) then add `toolchain` as a build requirement.
```
makes it pretty clear.

I'll switch out `gcc` because it looks like the failure was a fluke and add in `toolchain` since we're compiling. Assuming it passes we could merge this and then incorporate the Windows build and improvements to the patch you've added.

**Comment by jschueller** [comment]
Good!

**Comment by jschueller** [comment]
Care to merge this one so i can rebase ?

**Comment by ceholden** [comment]
@jschueller All set! Thanks!

**Pull request merged**
